services:
  geomapviewer:
    platform: linux/x86_64
    container_name: geomapviewer
    build:
      context: .
    environment:
      NEXT_PUBLIC_CMS_API: ${MAPVIEWER_CMS_API}
      BASE_PATH: ${MAPVIEWER_BASE_PATH}
      ASSET_PREFIX: ${MAPVIEWER_ASSET_PREFIX}
      ANALYTICS_PROPERTY_ID: ${ANALYTICS_PROPERTY_ID}
      BITLY_TOKEN: ${BITLY_TOKEN}
      GOOGLE_CUSTOM_SEARCH_CX: ${GOOGLE_CUSTOM_SEARCH_CX}
      GOOGLE_SEARCH_API_KEY: ${GOOGLE_SEARCH_API_KEY}
    ports:
      - ${PORT}:3000

# networks:
#     default:
#       name:  ${AHW_DOCKER_NETWORK}
#       external: true

